### ISSUE TITLE
confidential-smart-ehr example doesn't work

### ISSUE THREAD

**Issue by vadi2** [Vermonster/fhir-kit-client#96]
## Expected Behavior
It should work.

## Actual Behavior
`Error: Cannot find module 'query-string'`

## Steps to Reproduce the Problem

  1. `cd confidential-smart-ehr/`
  1. `yarn install`
  1. `yarn start`

```
vadi@volga:~/Programs$ git clone https://github.com/Vermonster/fhir-kit-client.git
Cloning into 'fhir-kit-client'...
remote: Enumerating objects: 136, done.
remote: Counting objects: 100% (136/136), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 1473 (delta 100), reused 95 (delta 72), pack-reused 1337
Receiving objects: 100% (1473/1473), 1.24 MiB | 2.48 MiB/s, done.
Resolving deltas: 100% (949/949), done.
vadi@volga:~/Programs$ cd fhir
bash: cd: fhir: No such file or directory
vadi@volga:~/Programs$ cd fhir-kit-client/
vadi@volga:~/Programs/fhir-kit-client$ cd examples/confidential-smart-ehr/
vadi@volga:~/Programs/fhir-kit-client/examples/confidential-smart-ehr$ yarn install
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Done in 0.70s.
vadi@volga:~/Programs/fhir-kit-client/examples/confidential-smart-ehr$ yarn start
yarn run v1.7.0
$ node confidential-smart-ehr-launch.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'query-string'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vadi/Programs/fhir-kit-client/lib/client.js:1:83)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
```

## Specifications
Ubuntu 18.04, yarn 1.7.0, node 8.11.3.

**Comment by Jammjammjamm** [comment]
This is happening because in the example, we require the local fhir-kit-client (`require('../../lib/client')`) rather than installing the client from npm (`require('fhir-kit-client')`), so running `yarn install` in the example doesn't install fhir-kit-client's dependencies. In order for the example to work, `yarn install` must have previously been run in the repo root.

**Comment by vadi2** [comment]
That worked. Thank you very much!

**Comment by Jammjammjamm** [comment]
I think we should leave this issue open. At a minimum we should correct the instructions for running the example.

**Comment by bkaney** [comment]
Fixed in https://github.com/Vermonster/fhir-kit-client/pull/101
